title:              Nihal Puram
email:              puramnihal@gmail.com
description:        Aerospace and Self-taught Machine Learning Engineer
author:             Nihal Puram
baseurl:            ""
url:                "https://realnihal.github.io"

# Social Profiles
twitter_username:   PuramNihal
github_username:    realnihal
facebook_username:  puram.16
instagram_username: realnihal16
linkedin_username:  Nihal Puram

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
